- name: Install deps
  hosts: odooserver
  become: yes
  tasks:
    - name: install deps
      apt:  pkg="python-unicodecsv"
            state=installed

- name: Clone Addons Repositories
  hosts: odooserver
  become: yes
  become_user: "{{ odoo_user }}"
  tasks:
    - name : clone beCloud repository
      git: repo=https://github.com/be-cloud-be/odoo-modules.git
           dest="/home/{{ odoo_user }}/addons/becloud"
           version="{{odoo_version}}"
      notify: Restart Odoo