- name: Odoo
  hosts: all
  become: yes
  roles:
    - odoo
vars:
    - odoo_version: 10.0
    - odoo_service: odoo
    - odoo_user: odoo
    - odoo_user_passwd: XXXXXXXXX
    - odoo_config_admin_passwd: admingit
    - odoo_config_xmlrpc_port: 8067
    - odoo_config_xmlrpcs_port: 8071
    - odoo_config_longpolling_port: 8072
    - odoo_config_db_user: odoo
    - odoo_user_sshkeys: /home/odoo/.ssh/id_rsa.pub