- name: Odoo
  hosts: all
  become: yes
  roles:
    - odoo
  vars:
    - odoo_version: 10.0
    - odoo_service: odoo
    - odoo_user: odoo10
    - odoo_config_admin_passwd: admingit
    - odoo_config_xmlrpc_port: 8079
    - odoo_config_xmlrpcs_port: 8081
    - odoo_config_longpolling_port: 8082
    - odoo_config_db_user: "{{ odoo_user }}"
    - odoo_user_sshkeys: "/home/{{ odoo_user }}/.ssh/id_rsa.pub"
    - odoo_config_addons_path:
        - "/home/{{ odoo_user }}/odoo/server/addons"
        - "/home/{{ odoo_user }}/odoo/addons"
        - "/home/{{ odoo_user }}/odoo/horizon"