- name: Odoo
  hosts: all
  become: yes
  roles:
    - odoo
  vars:
    - odoo_version: 10.0
    - odoo_config_admin_passwd: admingit
    - odoo_config_db_user: odoo
    - odoo_user_sshkeys: /home/odoo10/.ssh/id_rsa.pub