- name: Odoo
  hosts: odooserver
  become: yes
  roles:
    - odoo
  vars:
    - odoo_config_admin_passwd: "horizon-to-change"
    - odoo_repo_url: https://github.com/be-cloud-be/odoo.git
    - odoo_workdir: "/home/{{ odoo_user }}/odoo"
    - odoo_rootdir: "/home/{{ odoo_user }}/odoo"
    - odoo_repo_rev: "{{odoo_version}}"
    - odoo_repo_update: yes
    - odoo_config_unaccent: True
    - odoo_config_addons_path:
        - "/home/{{ odoo_user }}/odoo/openerp/addons"
        - "/home/{{ odoo_user }}/odoo/addons"
    - odoo_config_custom: {
      workers : "4",
    }