- name: Odoo
  hosts: odooserver
  become: yes
  roles:
    - odoo
  vars:
    - odoo_config_admin_passwd: "TODO" # TODO change this !!!
    - odoo_repo_url: https://github.com/be-cloud-be/odoo.git
    - odoo_workdir: "/home/{{ odoo_user }}/odoo"
    - odoo_rootdir: "/home/{{ odoo_user }}/odoo"
    - odoo_repo_rev: "{{odoo_version}}"
    - odoo_repo_update: yes
    - odoo_config_unaccent: True
    - odoo_config_xmlrpc_port : 8079
    - odoo_config_longpolling_port: 8092
    - odoo_config_addons_path:
        - "/home/{{ odoo_user }}/odoo/odoo/addons"
        - "/home/{{ odoo_user }}/odoo/addons"
        - "/home/{{ odoo_user }}/addons/becloud"
    - odoo_config_custom: {
      workers : "4",
    }