---

- name: Restart Odoo
  service:
    name: "{{ odoo_service }}"
    state: restarted
  when: odoo_init == True

- name: Restart Odoo System V
  systemd:
    name: "{{ odoo_service }}"
    enabled: yes
    masked: no